FROM prefecthq/prefect:sha-9b50ae1-python3.12

WORKDIR /app

COPY .env /app/.env
COPY flows/ /app/flows/
COPY dbt_pipeline/ /app/dbt_pipeline/

RUN pip install -r /app/flows/worker_requirements.txt

ENV PYTHONPATH=/app