FROM prefecthq/prefect:sha-9b50ae1-python3.12

WORKDIR /app

COPY .env /app/.env
COPY flows/ /app/flows/
COPY dbt_pipeline/ /app/dbt_pipeline/
COPY worker_requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt

ENV PYTHONPATH=/app