models:
  - name: terceirizados_bronze
    description: "Cópia simples dos brutos de terceirizados do governo federal carregados da CGU. Todos os dados estão como STRING para evitar erros de tipo. As transformações de tipo ocorrem na camada Silver."
    columns:
      - name: id_terc
        description: "Identificador do registro do terceirizado nesta base de dados"
        type: string
        data_tests:
          - unique
          - not_null
      
      - name: sg_orgao_sup_tabela_ug
        description: "Sigla do órgão superior da unidade gestora do terceirizado"
        type: string
      
      - name: cd_ug_gestora
        description: "Código da unidade gestora (proveniente do Sistema Integrado de Administração Financeira do Governo Federal - SIAFI) do terceirizado"
        type: string
      
      - name: nm_ug_tabela_ug
        description: "Nome da unidade gestora do terceirizado"
        type: string
      
      - name: sg_ug_gestora
        description: "Sigla da unidade gestora do terceirizado"
        type: string
      
      - name: nr_contrato
        description: "Número do contrato com a empresa terceirizada"
        type: string
      
      - name: nr_cnpj
        description: "Cnpj da empresa terceirizada"
        type: string
      
      - name: nm_razao_social
        description: "Razão Social da empresa terceirizada"
        type: string
      
      - name: nr_cpf
        description: "Cpf do terceirizado"
        type: string
      
      - name: nm_terceirizado
        description: "Nome completo do terceirizado"
        type: string
      
      - name: nm_categoria_profissional
        description: "Código da Classificação Brasileira de Ocupações (CBO) e descrição da categoria profissional do terceirizado"
        type: string
      
      - name: nm_escolaridade
        description: "Nível de escolaridade exigido pela ocupação do terceirizado"
        type: string
      
      - name: nr_jornada
        description: "Quantidade de horas semanais de trabalho do terceirizado"
        type: string
      
      - name: nm_unidade_prestacao
        description: "Descrição da unidade onde o terceirizado trabalha"
        type: string
      
      - name: vl_mensal_salario
        description: "Valor mensal do salário do terceirizado (R$)"
        type: string
        data_tests:
          - not_null
      
      - name: vl_mensal_custo
        description: "Custo total mensal do terceirizado (R$)"
        type: string
        data_tests:
          - not_null
      
      - name: Num_Mes_Carga
        description: "Número do mês da carga de dados"
        type: string
      
      - name: Mes_Carga
        description: "Mês da carga dos dados"
        type: string
      
      - name: Ano_Carga
        description: "Ano da carga dos dados"
        type: string

      - name: sg_orgao
        description: "Sigla do órgão onde o terceirizado trabalha"
        type: string
      
      - name: nm_orgao
        description: "Nome do órgão onde o terceirizado trabalha"
        type: string
      
      - name: cd_orgao_siafi
        description: "Código SIAFI do órgão onde o terceirizado trabalha"
        type: string
      
      - name: cd_orgao_siape
        description: "Código SIAPE (Sistema de Administração de Pessoal) do órgão onde o terceirizado trabalha"
        type: string
      
      - name: mes_referencia
        description: "Mês de referência dos dados fornecido pelo nome do arquivo de origem. Formato: YYYY-MM-01"
        type: date
        data_tests:
          - not_null

  - name: terceirizados_silver
    description: "Dados de de terceirizados do governo federal carregados da CGU com colunas transformadas para os tipos corretos"
    columns:
      - name: id_terceirizado
        description: "Identificador do registro do terceirizado nesta base de dados"
        type: integer
        data_tests:
          - unique
          - not_null

      - name: terceirizado_cpf
        description: "CPF do terceirizado."
        type: string

      - name: terceirizado_nome
        description: "Nome completo do terceirizado."
        type: string

      - name: terceirizado_categoria_profissional
        description: "Código da Classificação Brasileira de Ocupações (CBO) e descrição da categoria profissional do terceirizado"
        type: string

      - name: terceirizado_escolaridade
        description: "Nível de escolaridade exigido pela ocupação do terceirizado"
        type: string

      - name: terceirizado_salario
        description: "Valor mensal do salário do terceirizado (R$), convertido para tipo numérico"
        type: double
        data_tests:
          - not_null

      - name: terceirizado_custo
        description: "Custo total mensal do terceirizado (R$), convertido para tipo numérico"
        type: double
        data_tests:
          - not_null

      - name: jornada_horas
        description: "Quantidade de horas semanais de trabalho do terceirizado"
        type: integer

      - name: empresa_cnpj
        description: "CNPJ da empresa terceirizada"
        type: string

      - name: empresa_razao_social
        description: "Razão Social da empresa terceirizada"
        type: string

      - name: contrato_numero
        description: "Número do contrato com a empresa terceirizada"
        type: string

      - name: orgao_superior_sigla
        description: "Sigla do órgão superior da unidade gestora do terceirizado"
        type: string

      - name: unidade_gestora_sigla
        description: "Sigla da unidade gestora do terceirizado"
        type: string

      - name: unidade_gestora_nome
        description: "Nome da unidade gestora do terceirizado"
        type: string

      - name: unidade_gestora_codigo
        description: "Código da unidade gestora (SIAFI) do terceirizado"
        type: string

      - name: orgao_sigla
        description: "Sigla do órgão onde o terceirizado trabalha"
        type: string

      - name: orgao_nome
        description: "Nome do órgão onde o terceirizado trabalha"
        type: string

      - name: orgao_codigo_siafi
        description: "Código SIAFI do órgão onde o terceirizado trabalha"
        type: string

      - name: orgao_codigo_siape
        description: "Código SIAPE do órgão onde o terceirizado trabalha"
        type: string

      - name: unidade_prestacao_nome
        description: "Descrição da unidade onde o terceirizado trabalha"
        type: string

      - name: mes_carga_tabela
        description: "Mês da carga dos dados construído a partir de Ano_Carga e Num_Mes_Carga da tabela Bronze"
        type: date
        data_tests:
          - not_null

      - name: mes_referencia
        description: "Mês de referência dos dados fornecido pelo nome do arquivo de origem. Formato: YYYY-MM-01"
        type: date
        data_tests:
          - not_null

  - name: terceirizados_gold
    description: "Dados de terceirizados do governo federal com valores nulos substituídos por 'Não informado' e colunas consolidadas da camada Silver. Resultado da camada Gold, pronto para consultas."
    columns:
    - name: id_terceirizado
      description: "Identificador do registro do terceirizado"
      type: integer

    - name: terceirizado_cpf
      description: "CPF do terceirizado. Valores nulos substituídos por 'Não informado'."
      type: string

    - name: terceirizado_nome
      description: "Nome completo do terceirizado. Valores nulos substituídos por 'Não informado'."
      type: string

    - name: terceirizado_categoria_profissional
      description: "Código da CBO e descrição da categoria profissional do terceirizado. Valores nulos substituídos por 'Não informado'."
      type: string

    - name: terceirizado_escolaridade
      description: "Nível de escolaridade exigido. Valores nulos substituídos por 'Não informado'."
      type: string

    - name: terceirizado_salario
      description: "Valor mensal do salário do terceirizado (R$)"
      type: double

    - name: terceirizado_custo
      description: "Custo total mensal do terceirizado (R$)"
      type: double

    - name: jornada_horas
      description: "Quantidade de horas semanais de trabalho do terceirizado"
      type: integer

    - name: empresa_cnpj
      description: "CNPJ da empresa terceirizada. Valores nulos substituídos por 'Não informado'."
      type: string

    - name: empresa_razao_social
      description: "Razão social da empresa terceirizada. Valores nulos substituídos por 'Não informado'."
      type: string

    - name: contrato_numero
      description: "Número do contrato com a empresa terceirizada. Valores nulos substituídos por 'Não informado'."
      type: string

    - name: orgao_superior_sigla
      description: "Sigla do órgão superior da unidade gestora do terceirizado. Valores nulos substituídos por 'Não informado'."
      type: string

    - name: unidade_gestora_sigla
      description: "Sigla da unidade gestora do terceirizado. Valores nulos substituídos por 'Não informado'."
      type: string

    - name: unidade_gestora_nome
      description: "Nome da unidade gestora do terceirizado. Valores nulos substituídos por 'Não informado'."
      type: string

    - name: unidade_gestora_codigo
      description: "Código da unidade gestora (SIAFI) do terceirizado. Valores nulos substituídos por 'Não informado'."
      type: string

    - name: orgao_sigla
      description: "Sigla do órgão onde o terceirizado trabalha. Valores nulos substituídos por 'Não informado'."
      type: string

    - name: orgao_nome
      description: "Nome do órgão onde o terceirizado trabalha. Valores nulos substituídos por 'Não informado'."
      type: string

    - name: orgao_codigo_siafi
      description: "Código SIAFI do órgão onde o terceirizado trabalha. Valores nulos substituídos por 'Não informado'."
      type: string

    - name: orgao_codigo_siape
      description: "Código SIAPE do órgão onde o terceirizado trabalha. Valores nulos substituídos por 'Não informado'."
      type: string

    - name: unidade_prestacao_nome
      description: "Descrição da unidade onde o terceirizado trabalha. Valores nulos substituídos por 'Não informado'."
      type: string

    - name: mes_carga
      description: "Mês da carga dos dados. Utiliza `mes_carga_tabela` da Silver ou, se nulo, `mes_referencia`."
      type: date
      data_tests:
        - not_null