models:
  - name: terceirizados_bronze
    description: "Cópia simples dos dados brutos de terceirizados carregada da CGU"
    columns:
      - name: id_terc
        description: "Identificador do registro do terceirizado nesta base de dados"
        data_tests:
          - unique
          - not_null
      
      - name: sg_orgao_sup_tabela_ug
        description: "Sigla do órgão superior da unidade gestora do terceirizado"
      
      - name: cd_ug_gestora
        description: "Código da unidade gestora (proveniente do Sistema Integrado de Administração Financeira do Governo Federal - SIAFI) do terceirizado"
      
      - name: nm_ug_tabela_ug
        description: "Nome da unidade gestora do terceirizado"
      
      - name: sg_ug_gestora
        description: "Sigla da unidade gestora do terceirizado"
      
      - name: nr_contrato
        description: "Número do contrato com a empresa terceirizada"
      
      - name: nr_cnpj
        description: "Cnpj da empresa terceirizada"
      
      - name: nm_razao_social
        description: "Razão Social da empresa terceirizada"
      
      - name: nr_cpf
        description: "Cpf do terceirizado"
      
      - name: nm_terceirizado
        description: "Nome completo do terceirizado"
      
      - name: nm_categoria_profissional
        description: "Código da Classificação Brasileira de Ocupações (CBO) e descrição da categoria profissional do terceirizado"
      
      - name: nm_escolaridade
        description: "Nível de escolaridade exigido pela ocupação do terceirizado"
      
      - name: nr_jornada
        description: "Quantidade de horas semanais de trabalho do terceirizado"
      
      - name: nm_unidade_prestacao
        description: "Descrição da unidade onde o terceirizado trabalha"
      
      - name: vl_mensal_salario
        description: "Valor mensal do salário do terceirizado (R$)"
        data_tests:
          - not_null
      
      - name: vl_mensal_custo
        description: "Custo total mensal do terceirizado (R$)"
        data_tests:
          - not_null
      
      - name: Num_Mes_Carga
        description: "Número do mês da carga de dados"
      
      - name: Mes_Carga
        description: "Mês da carga dos dados"
      
      - name: Ano_Carga
        description: "Ano da carga dos dados"

      - name: sg_orgao
        description: "Sigla do órgão onde o terceirizado trabalha"
      
      - name: nm_orgao
        description: "Nome do órgão onde o terceirizado trabalha"
      
      - name: cd_orgao_siafi
        description: "Código SIAFI do órgão onde o terceirizado trabalha"
      
      - name: cd_orgao_siape
        description: "Código SIAPE (Sistema de Administração de Pessoal) do órgão onde o terceirizado trabalha"
      
      - name: mes_referencia
        description: "Mês de referência dos dados fornecido pelo nome do arquivo de origem"
        data_tests:
          - not_null

  - name: terceirizados_silver
    description: "Dados de terceirizados carregada da CGU com colunas transformadas para os tipos corretos"
    columns:
      - name: id_terc
        description: "Identificador do registro do terceirizado nesta base de dados"
        data_tests:
          - unique
          - not_null
      
      - name: sg_orgao_sup_tabela_ug
        description: "Sigla do órgão superior da unidade gestora do terceirizado"
      
      - name: cd_ug_gestora
        description: "Código da unidade gestora (proveniente do Sistema Integrado de Administração Financeira do Governo Federal - SIAFI) do terceirizado"
      
      - name: nm_ug_tabela_ug
        description: "Nome da unidade gestora do terceirizado"
      
      - name: sg_ug_gestora
        description: "Sigla da unidade gestora do terceirizado"
      
      - name: nr_contrato
        description: "Número do contrato com a empresa terceirizada"
      
      - name: nr_cnpj
        description: "Cnpj da empresa terceirizada"
      
      - name: nm_razao_social
        description: "Razão Social da empresa terceirizada"
      
      - name: nr_cpf
        description: "Cpf do terceirizado"
      
      - name: nm_terceirizado
        description: "Nome completo do terceirizado"
      
      - name: nm_categoria_profissional
        description: "Código da Classificação Brasileira de Ocupações (CBO) e descrição da categoria profissional do terceirizado"
      
      - name: nm_escolaridade
        description: "Nível de escolaridade exigido pela ocupação do terceirizado"
      
      - name: nr_jornada
        description: "Quantidade de horas semanais de trabalho do terceirizado"
      
      - name: nm_unidade_prestacao
        description: "Descrição da unidade onde o terceirizado trabalha"
      
      - name: vl_mensal_salario
        description: "Valor mensal do salário do terceirizado (R$)"
        data_tests:
          - not_null
      
      - name: vl_mensal_custo
        description: "Custo total mensal do terceirizado (R$)"
        data_tests:
          - not_null
      
      - name: mes_carga_tabela
        description: "Mês da carga dos dados construído pela composição das colunas descritivas de mês e ano da carga na tabela bronze"
        data_tests:
          - not_null
      
      - name: sg_orgao
        description: "Sigla do órgão onde o terceirizado trabalha"
      
      - name: nm_orgao
        description: "Nome do órgão onde o terceirizado trabalha"
      
      - name: cd_orgao_siafi
        description: "Código SIAFI do órgão onde o terceirizado trabalha"
      
      - name: cd_orgao_siape
        description: "Código SIAPE (Sistema de Administração de Pessoal) do órgão onde o terceirizado trabalha"
      
      - name: mes_referencia
        description: "Mês de referência dos dados fornecido pelo nome do arquivo de origem"

  - name: terceirizados_gold
    description: "Dados de terceirizados carregada da CGU com colunas prontas para consumo"
    columns:
      - name: id_terc
        description: "Identificador do registro do terceirizado nesta base de dados"
      
      - name: sg_orgao_sup_tabela_ug
        description: "Sigla do órgão superior da unidade gestora do terceirizado"
      
      - name: cd_ug_gestora
        description: "Código da unidade gestora (proveniente do Sistema Integrado de Administração Financeira do Governo Federal - SIAFI) do terceirizado"
      
      - name: nm_ug_tabela_ug
        description: "Nome da unidade gestora do terceirizado"
      
      - name: sg_ug_gestora
        description: "Sigla da unidade gestora do terceirizado"
      
      - name: nr_contrato
        description: "Número do contrato com a empresa terceirizada"
      
      - name: nr_cnpj
        description: "Cnpj da empresa terceirizada"
      
      - name: nm_razao_social
        description: "Razão Social da empresa terceirizada"
      
      - name: nr_cpf
        description: "Cpf do terceirizado"
      
      - name: nm_terceirizado
        description: "Nome completo do terceirizado"
      
      - name: nm_categoria_profissional
        description: "Código da Classificação Brasileira de Ocupações (CBO) e descrição da categoria profissional do terceirizado"
      
      - name: nm_escolaridade
        description: "Nível de escolaridade exigido pela ocupação do terceirizado"
      
      - name: nr_jornada
        description: "Quantidade de horas semanais de trabalho do terceirizado"
      
      - name: nm_unidade_prestacao
        description: "Descrição da unidade onde o terceirizado trabalha"
      
      - name: vl_mensal_salario
        description: "Valor mensal do salário do terceirizado (R$)"
      
      - name: vl_mensal_custo
        description: "Custo total mensal do terceirizado (R$)"
      
      - name: sg_orgao
        description: "Sigla do órgão onde o terceirizado trabalha"
      
      - name: nm_orgao
        description: "Nome do órgão onde o terceirizado trabalha"
      
      - name: cd_orgao_siafi
        description: "Código SIAFI do órgão onde o terceirizado trabalha"
      
      - name: cd_orgao_siape
        description: "Código SIAPE (Sistema de Administração de Pessoal) do órgão onde o terceirizado trabalha"
      
      - name: mes_carga
        description: "Mês de carga dos dados"